#!/bin/sh

while :
do

clear

echo '### some tools'
echo 'ci - .create .i386-wine-pkg.tar.xz'
echo 'upd - close techno'
echo 'exit - close techno'
echo ''
echo -n 'Choose your number: '
 read ans
 case "$ans" in
  1)
  export XZ_OPT=-9 
  tar cvJf .i386-wine-pkg.tar.xz .i386-wine-pkg
  ;;
 upd)
   ### update techno
   fetch https://github.com/bsdver/so/archive/refs/heads/main.zip
   unzip main.zip
   mv so-main/techno .techno
   sudo chmod +x .techno
   rm -rf so-main
   rm main.zip
   xterm -geometry 73x41-0-25 -e ./.techno &
   sleep 2
   break
 ;;
 exit)
   echo 'Exit.'
   sleep 1
   break
 ;;
 *)
   echo "Error. Please, type number. Start again..."
 ;;
 esac
done
